### ISSUE TITLE
Select Level Scene

### ISSUE THREAD

**Issue by norangebit** [virusdefense/virusdefense#25]
# To-Do

- [x] Add Level Button ([4fae09b](https://github.com/virusdefense/virusdefense/commit/4fae09bc942745579c8e69edea052ff2224b0a62))
- [x] Add Select Level Scene ([ad3cf2d](https://github.com/virusdefense/virusdefense/commit/ad3cf2dba3bd1cfc6ad318fcc02af009f55d0a16))
- [x] Add Resource Files for Level 1([a349dbc](https://github.com/virusdefense/virusdefense/commit/a349dbcfc4951f0263ebc9e9f8aecdb1b6c72424))
- [x] Add Resource Files for Level 2 ([cdc54e1](https://github.com/virusdefense/virusdefense/commit/cdc54e16de99c1856cbe6dc1f26c4ccdf406fb59))
- [x] Add Resource Files for Level 3 ([1f64eab](https://github.com/virusdefense/virusdefense/commit/1f64eab0f7a2b60fbdb66e3a3c3e6ba123bfe6f5))
- [x] Add Behavior to Level Button ([4449da5](https://github.com/virusdefense/virusdefense/commit/4449da59ed20896fd31267e600fc75b28369796e))
- [x] Load Level Scene on Click ([370b0f9](https://github.com/virusdefense/virusdefense/commit/370b0f9a8095d537b4bbea2654cbee008a62b22c))
- [x] Add main menu behavior (see #26) ([6fa7b5b](https://github.com/virusdefense/virusdefense/commit/6fa7b5b8559743d90ae07869c6aa77d70189a0f0))
