### ISSUE TITLE
Upgrade store

### ISSUE THREAD

**Issue by norangebit** [virusdefense/virusdefense#28]
# To-Do

- [x] Add TowerLevel button ([1f35cd0](https://github.com/virusdefense/virusdefense/commit/1f35cd01cbde6d051aee8884d99a7d12da96e170))
- [x] Add Upgrade store scene ([9ea37ca](https://github.com/virusdefense/virusdefense/commit/9ea37ca8d32bcd83cf7e01cc5f383e943013340b))
- [x] Add behavior to TowerLevel button ([838a419a](https://github.com/virusdefense/virusdefense/commit/838a419a84928cf9cc6185c406e6f16ae3b0bb58))
- [x] Add behavior to upgrade store scene ([11a88feb](https://github.com/virusdefense/virusdefense/commit/11a88feb08a0a0d4f86562dccd45b2b638a7b2ed))
- [x] Add link to the store from the main menu
- [x] Add link from store to the main menu

the last two points need #27 to be merged.
